### ISSUE TITLE
I couldn't find a hardware device. You don't have a valid microphone

### ISSUE THREAD

**Issue by Dani3lSun** [StevenHickson/PiAUISuite#28]
During the installation process, exactly when asking "Do you want to set up and check the speech recognition options?" I get the error message "I couldn't find a hardware device. You don't have a valid microphone" and the installer closes. I have an USB sound card plugged in (for headphone and microphone), and the hardware seems to work correctly. card number is 0.

List Devices:
Command: aplay -l
***\* Liste der Hardware-Geräte (PLAYBACK) ****
Karte 0: Device [USB PnP Sound Device], Gerät 0: USB Audio [USB Audio]
  Sub-Geräte: 1/1
  Sub-Gerät #0: subdevice #0
Karte 1: ALSA [bcm2835 ALSA], Gerät 0: bcm2835 ALSA [bcm2835 ALSA]
  Sub-Geräte: 8/8
  Sub-Gerät #0: subdevice #0
  Sub-Gerät #1: subdevice #1
  Sub-Gerät #2: subdevice #2
  Sub-Gerät #3: subdevice #3
  Sub-Gerät #4: subdevice #4
  Sub-Gerät #5: subdevice #5
  Sub-Gerät #6: subdevice #6
  Sub-Gerät #7: subdevice #7
Karte 1: ALSA [bcm2835 ALSA], Gerät 1: bcm2835 ALSA [bcm2835 IEC958/HDMI]
  Sub-Geräte: 1/1
  Sub-Gerät #0: subdevice #0

Command: arecord -l
***\* Liste der Hardware-Geräte (CAPTURE) ****
Karte 0: Device [USB PnP Sound Device], Gerät 0: USB Audio [USB Audio]
  Sub-Geräte: 1/1
  Sub-Gerät #0: subdevice #0

Take a record:
Command: arecord -D plughw:0,0 -f cd test.wav
Works perfectly.

Play the recorded wav-file:
Command: aplay test.wav
Works also.

Config Files:
/etc/modprobe.d/alsa-base.conf
I edited it to 
options snd-usb-audio index=0

/etc/asound.conf
I added this:
pcm.!default {
type plug
slave {
pcm "hw:0,0"
}
}
ctl.!default {
type hw
card 0
}

So I think that my audio input and output configured correctly...What else can be the mistake?
Thanks for your help!

**Comment by craql** [comment]
Hey Steve, it seems like you've got a great plugin, but I can't seem to get it working. I'm using a Pi 2. is it not compatible with that model? Also, the usb headset I'm using records and plays back audio just fine. Whenever I run voicecommand, it returns with "No translation" and no audio response.

Thanks for your help.
