### ISSUE TITLE
Youtube videos don't work

### ISSUE THREAD

**Issue by IonicaBizau** [StevenHickson/PiAUISuite#46]
When trying to access the `yt://youtube.com/watch?...` urls in Midori, a black window is opened, but it closes immediately.

I [followed the instructions here](http://stevenhickson.blogspot.ro/2013/06/playing-youtube-videos-in-browser-on.html).

**Comment by camdixon** [comment]
Can you open youtube in Midori browser normally?   Have you tried manually doing this using youtube play or youtube safe?   Just curious.  Which system are you on?

**Comment by IonicaBizau** [comment]
I'm using Raspbian. But I fixed the issue using `mps-youtube`: https://github.com/IonicaBizau/raspberry-pi/blob/master/story/6.%20Watching%20YouTube%20videos.md

Thanks!
